language: android

sudo: false

jdk:
    - oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22

    # Additional Components
    - extra

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request? $TRAVIS_PULL_REQUEST"
    - echo "Travis tag $TRAVIS_TAG"
    - gradle :library:assembleRelease :library:uploadArchives

notifications:
  email:
    - toxicbakery@gmail.com